### ISSUE TITLE
运行infer,py出现问题

### ISSUE THREAD

**Issue by Pandoravirus-N-T** [SCIR-HI/Med-ChatGLM#59]
你好作者，想请请教一下当我运行代码时出现如下报错是什么原因呢
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\Med-ChatGLM-main\Med-ChatGLM-main\infer.py", line 4, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 794, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\transformers\configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\transformers\configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\transformers\utils\hub.py", line 369, in cached_file
    raise EnvironmentError(
OSError: ./model does not appear to have a file named config.json. Checkout 'https://huggingface.co/./model/tree/None' for available files.

**Comment by Yue-ming-han** [comment]
我也是这个问题，应该是缺了config.json这个文件，但我也还没解决
